name: build_and_guess
version: '${version}'
main: org.mick.build_and_guess.Build_and_guess
api-version: '1.20'

commands:
  chat_manger:
    description: 打开聊天
    usage: /<command>

  start:
    description: 开始建筑猜猜乐游戏
    usage: /<command>

  left:
    description: 调整剩余时间
    usage: /<command>

  game_time:
    description: 调整单局时间
    usage: /<command>